// Code generated by rpcgen. DO NOT EDIT.

//go:build !tinygo

package setup

import rpc "github.com/0magnet/gobrpc"

// registerTransportGateway registers *TransportGateway with the reflection-based net/rpc server.
func registerTransportGateway(rpcSrv *rpc.Server, rpcName string, rpcRcvr *TransportGateway) error {
	return rpcSrv.RegisterName(rpcName, rpcRcvr)
}
