// Code generated by rpcgen. DO NOT EDIT.

//go:build tinygo

package setup

import (
	"encoding/gob"

	rpc "github.com/0magnet/gobrpc"
)

// registerTransportGateway registers each net/rpc method of *TransportGateway as a reflection-free handler.
func registerTransportGateway(rpcSrv *rpc.Server, rpcName string, rpcRcvr *TransportGateway) error {
	rpcSrv.HandleFunc(rpcName+".AddTransport", func(rpcDec *gob.Decoder) (interface{}, error) {
		var rpcArg TransportRequest
		if err := rpcDec.Decode(&rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(TransportResponse)
		return rpcReply, rpcRcvr.AddTransport(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".GetTransports", func(rpcDec *gob.Decoder) (interface{}, error) {
		var rpcArg struct{}
		if err := rpcDec.Decode(&rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new([]TransportResponse)
		return rpcReply, rpcRcvr.GetTransports(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".RemoveTransport", func(rpcDec *gob.Decoder) (interface{}, error) {
		var rpcArg UUIDRequest
		if err := rpcDec.Decode(&rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(BoolResponse)
		return rpcReply, rpcRcvr.RemoveTransport(rpcArg, rpcReply)
	})
	return nil
}
