// Code generated by rpcgen. DO NOT EDIT.

//go:build tinygo

package api

import (
	"encoding/gob"

	rpc "github.com/0magnet/gobrpc"
)

// registerSetupRPCGateway registers each net/rpc method of *SetupRPCGateway as a reflection-free handler.
func registerSetupRPCGateway(rpcSrv *rpc.Server, rpcName string, rpcRcvr *SetupRPCGateway) error {
	rpcSrv.HandleFunc(rpcName+".AddTransport", func(rpcDec *gob.Decoder) (interface{}, error) {
		rpcArg := new(TransportSetupRequest)
		if err := rpcDec.Decode(rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(TransportSetupResponse)
		return rpcReply, rpcRcvr.AddTransport(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".GetTransports", func(rpcDec *gob.Decoder) (interface{}, error) {
		rpcArg := new(GetTransportsRequest)
		if err := rpcDec.Decode(rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(GetTransportsResponse)
		return rpcReply, rpcRcvr.GetTransports(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".HealthCheck", func(rpcDec *gob.Decoder) (interface{}, error) {
		rpcArg := new(HealthCheckArgs)
		if err := rpcDec.Decode(rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(HealthCheckReply)
		return rpcReply, rpcRcvr.HealthCheck(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".RemoveTransport", func(rpcDec *gob.Decoder) (interface{}, error) {
		rpcArg := new(RemoveTransportRequest)
		if err := rpcDec.Decode(rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(struct{})
		return rpcReply, rpcRcvr.RemoveTransport(rpcArg, rpcReply)
	})
	return nil
}
