// Code generated by rpcgen. DO NOT EDIT.

//go:build tinygo

package api

import (
	"encoding/gob"

	rpc "github.com/0magnet/gobrpc"
)

// registerSetupRPCGateway registers each net/rpc method of *SetupRPCGateway as a reflection-free handler.
func registerSetupRPCGateway(rpcSrv *rpc.Server, rpcName string, rpcRcvr *SetupRPCGateway) error {
	rpcSrv.HandleCall(rpcName+".AddTransport", func(rpcDec *gob.Decoder) (rpc.CallFunc, error) {
		rpcArg := new(TransportSetupRequest)
		if err := rpcDec.Decode(rpcArg); err != nil {
			return nil, err
		}
		return func() (any, error) {
			rpcReply := new(TransportSetupResponse)
			return rpcReply, rpcRcvr.AddTransport(rpcArg, rpcReply)
		}, nil
	})
	rpcSrv.HandleCall(rpcName+".GetTransports", func(rpcDec *gob.Decoder) (rpc.CallFunc, error) {
		rpcArg := new(GetTransportsRequest)
		if err := rpcDec.Decode(rpcArg); err != nil {
			return nil, err
		}
		return func() (any, error) {
			rpcReply := new(GetTransportsResponse)
			return rpcReply, rpcRcvr.GetTransports(rpcArg, rpcReply)
		}, nil
	})
	rpcSrv.HandleCall(rpcName+".HealthCheck", func(rpcDec *gob.Decoder) (rpc.CallFunc, error) {
		rpcArg := new(HealthCheckArgs)
		if err := rpcDec.Decode(rpcArg); err != nil {
			return nil, err
		}
		return func() (any, error) {
			rpcReply := new(HealthCheckReply)
			return rpcReply, rpcRcvr.HealthCheck(rpcArg, rpcReply)
		}, nil
	})
	rpcSrv.HandleCall(rpcName+".RemoveTransport", func(rpcDec *gob.Decoder) (rpc.CallFunc, error) {
		rpcArg := new(RemoveTransportRequest)
		if err := rpcDec.Decode(rpcArg); err != nil {
			return nil, err
		}
		return func() (any, error) {
			rpcReply := new(struct{})
			return rpcReply, rpcRcvr.RemoveTransport(rpcArg, rpcReply)
		}, nil
	})
	return nil
}
