// Code generated by rpcgen. DO NOT EDIT.

//go:build !tinygo

package api

import rpc "github.com/0magnet/gobrpc"

// registerSetupRPCGateway registers *SetupRPCGateway with the reflection-based net/rpc server.
func registerSetupRPCGateway(rpcSrv *rpc.Server, rpcName string, rpcRcvr *SetupRPCGateway) error {
	return rpcSrv.RegisterName(rpcName, rpcRcvr)
}
