// Code generated by rpcgen. DO NOT EDIT.

//go:build tinygo

package node

import (
	"encoding/gob"

	rpc "github.com/0magnet/gobrpc"
	"github.com/skycoin/skycoin/src/cipher"

	"github.com/skycoin/skywire/pkg/cxo/skyobject/registry"
)

// registerNodeRPC registers each net/rpc method of *RPC as a reflection-free handler.
func registerNodeRPC(rpcSrv *rpc.Server, rpcName string, rpcRcvr *RPC) error {
	rpcSrv.HandleFunc(rpcName+".Config", func(rpcDec *gob.Decoder) (interface{}, error) {
		var rpcArg struct{}
		if err := rpcDec.Decode(&rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(Config)
		return rpcReply, rpcRcvr.Config(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".Connections", func(rpcDec *gob.Decoder) (interface{}, error) {
		var rpcArg struct{}
		if err := rpcDec.Decode(&rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new([]string)
		return rpcReply, rpcRcvr.Connections(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".ConnectionsOfFeed", func(rpcDec *gob.Decoder) (interface{}, error) {
		var rpcArg cipher.PubKey
		if err := rpcDec.Decode(&rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new([]string)
		return rpcReply, rpcRcvr.ConnectionsOfFeed(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".DontShare", func(rpcDec *gob.Decoder) (interface{}, error) {
		var rpcArg cipher.PubKey
		if err := rpcDec.Decode(&rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(struct{})
		return rpcReply, rpcRcvr.DontShare(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".Feeds", func(rpcDec *gob.Decoder) (interface{}, error) {
		var rpcArg struct{}
		if err := rpcDec.Decode(&rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new([]cipher.PubKey)
		return rpcReply, rpcRcvr.Feeds(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".IsSharing", func(rpcDec *gob.Decoder) (interface{}, error) {
		var rpcArg cipher.PubKey
		if err := rpcDec.Decode(&rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(bool)
		return rpcReply, rpcRcvr.IsSharing(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".Share", func(rpcDec *gob.Decoder) (interface{}, error) {
		var rpcArg cipher.PubKey
		if err := rpcDec.Decode(&rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(struct{})
		return rpcReply, rpcRcvr.Share(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".Shutdown", func(rpcDec *gob.Decoder) (interface{}, error) {
		var rpcArg struct{}
		if err := rpcDec.Decode(&rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(struct{})
		return rpcReply, rpcRcvr.Shutdown(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".Stat", func(rpcDec *gob.Decoder) (interface{}, error) {
		var rpcArg struct{}
		if err := rpcDec.Decode(&rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(Stat)
		return rpcReply, rpcRcvr.Stat(rpcArg, rpcReply)
	})
	return nil
}

// registerTCPRPC registers each net/rpc method of *TCPRPC as a reflection-free handler.
func registerTCPRPC(rpcSrv *rpc.Server, rpcName string, rpcRcvr *TCPRPC) error {
	rpcSrv.HandleFunc(rpcName+".Address", func(rpcDec *gob.Decoder) (interface{}, error) {
		var rpcArg struct{}
		if err := rpcDec.Decode(&rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(string)
		return rpcReply, rpcRcvr.Address(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".Connect", func(rpcDec *gob.Decoder) (interface{}, error) {
		var rpcArg string
		if err := rpcDec.Decode(&rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(struct{})
		return rpcReply, rpcRcvr.Connect(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".Disconnect", func(rpcDec *gob.Decoder) (interface{}, error) {
		var rpcArg string
		if err := rpcDec.Decode(&rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(struct{})
		return rpcReply, rpcRcvr.Disconnect(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".RemoteFeeds", func(rpcDec *gob.Decoder) (interface{}, error) {
		var rpcArg string
		if err := rpcDec.Decode(&rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new([]cipher.PubKey)
		return rpcReply, rpcRcvr.RemoteFeeds(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".Subscribe", func(rpcDec *gob.Decoder) (interface{}, error) {
		var rpcArg ConnFeed
		if err := rpcDec.Decode(&rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(struct{})
		return rpcReply, rpcRcvr.Subscribe(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".Unsubscribe", func(rpcDec *gob.Decoder) (interface{}, error) {
		var rpcArg ConnFeed
		if err := rpcDec.Decode(&rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(struct{})
		return rpcReply, rpcRcvr.Unsubscribe(rpcArg, rpcReply)
	})
	return nil
}

// registerUDPRPC registers each net/rpc method of *UDPRPC as a reflection-free handler.
func registerUDPRPC(rpcSrv *rpc.Server, rpcName string, rpcRcvr *UDPRPC) error {
	rpcSrv.HandleFunc(rpcName+".Address", func(rpcDec *gob.Decoder) (interface{}, error) {
		var rpcArg struct{}
		if err := rpcDec.Decode(&rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(string)
		return rpcReply, rpcRcvr.Address(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".Connect", func(rpcDec *gob.Decoder) (interface{}, error) {
		var rpcArg string
		if err := rpcDec.Decode(&rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(struct{})
		return rpcReply, rpcRcvr.Connect(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".Disconnect", func(rpcDec *gob.Decoder) (interface{}, error) {
		var rpcArg string
		if err := rpcDec.Decode(&rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(struct{})
		return rpcReply, rpcRcvr.Disconnect(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".RemoteFeeds", func(rpcDec *gob.Decoder) (interface{}, error) {
		var rpcArg string
		if err := rpcDec.Decode(&rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new([]cipher.PubKey)
		return rpcReply, rpcRcvr.RemoteFeeds(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".Subscribe", func(rpcDec *gob.Decoder) (interface{}, error) {
		var rpcArg ConnFeed
		if err := rpcDec.Decode(&rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(struct{})
		return rpcReply, rpcRcvr.Subscribe(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".Unsubscribe", func(rpcDec *gob.Decoder) (interface{}, error) {
		var rpcArg ConnFeed
		if err := rpcDec.Decode(&rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(struct{})
		return rpcReply, rpcRcvr.Unsubscribe(rpcArg, rpcReply)
	})
	return nil
}

// registerRootRPC registers each net/rpc method of *RootRPC as a reflection-free handler.
func registerRootRPC(rpcSrv *rpc.Server, rpcName string, rpcRcvr *RootRPC) error {
	rpcSrv.HandleFunc(rpcName+".Last", func(rpcDec *gob.Decoder) (interface{}, error) {
		var rpcArg cipher.PubKey
		if err := rpcDec.Decode(&rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(registry.Root)
		return rpcReply, rpcRcvr.Last(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".Show", func(rpcDec *gob.Decoder) (interface{}, error) {
		var rpcArg RootSelector
		if err := rpcDec.Decode(&rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(registry.Root)
		return rpcReply, rpcRcvr.Show(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".Tree", func(rpcDec *gob.Decoder) (interface{}, error) {
		var rpcArg RootSelector
		if err := rpcDec.Decode(&rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(string)
		return rpcReply, rpcRcvr.Tree(rpcArg, rpcReply)
	})
	return nil
}

// registerDMSGRPC registers each net/rpc method of *DMSGRPC as a reflection-free handler.
func registerDMSGRPC(rpcSrv *rpc.Server, rpcName string, rpcRcvr *DMSGRPC) error {
	rpcSrv.HandleFunc(rpcName+".Connect", func(rpcDec *gob.Decoder) (interface{}, error) {
		var rpcArg cipher.PubKey
		if err := rpcDec.Decode(&rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(struct{})
		return rpcReply, rpcRcvr.Connect(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".Connections", func(rpcDec *gob.Decoder) (interface{}, error) {
		var rpcArg struct{}
		if err := rpcDec.Decode(&rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new([]cipher.PubKey)
		return rpcReply, rpcRcvr.Connections(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".Subscribe", func(rpcDec *gob.Decoder) (interface{}, error) {
		var rpcArg DMSGConnFeed
		if err := rpcDec.Decode(&rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(struct{})
		return rpcReply, rpcRcvr.Subscribe(rpcArg, rpcReply)
	})
	return nil
}
