// Code generated by rpcgen. DO NOT EDIT.

//go:build !tinygo

package node

import rpc "github.com/0magnet/gobrpc"

// registerNodeRPC registers *RPC with the reflection-based net/rpc server.
func registerNodeRPC(rpcSrv *rpc.Server, rpcName string, rpcRcvr *RPC) error {
	return rpcSrv.RegisterName(rpcName, rpcRcvr)
}

// registerTCPRPC registers *TCPRPC with the reflection-based net/rpc server.
func registerTCPRPC(rpcSrv *rpc.Server, rpcName string, rpcRcvr *TCPRPC) error {
	return rpcSrv.RegisterName(rpcName, rpcRcvr)
}

// registerUDPRPC registers *UDPRPC with the reflection-based net/rpc server.
func registerUDPRPC(rpcSrv *rpc.Server, rpcName string, rpcRcvr *UDPRPC) error {
	return rpcSrv.RegisterName(rpcName, rpcRcvr)
}

// registerRootRPC registers *RootRPC with the reflection-based net/rpc server.
func registerRootRPC(rpcSrv *rpc.Server, rpcName string, rpcRcvr *RootRPC) error {
	return rpcSrv.RegisterName(rpcName, rpcRcvr)
}

// registerDMSGRPC registers *DMSGRPC with the reflection-based net/rpc server.
func registerDMSGRPC(rpcSrv *rpc.Server, rpcName string, rpcRcvr *DMSGRPC) error {
	return rpcSrv.RegisterName(rpcName, rpcRcvr)
}
