// Code generated by rpcgen. DO NOT EDIT.

//go:build !tinygo

package visor

import rpc "github.com/0magnet/gobrpc"

// registerVisorRPC registers *RPC with the reflection-based net/rpc server.
func registerVisorRPC(rpcSrv *rpc.Server, rpcName string, rpcRcvr *RPC) error {
	return rpcSrv.RegisterName(rpcName, rpcRcvr)
}

// registerTPSRPCGateway registers *TPSRPCGateway with the reflection-based net/rpc server.
func registerTPSRPCGateway(rpcSrv *rpc.Server, rpcName string, rpcRcvr *TPSRPCGateway) error {
	return rpcSrv.RegisterName(rpcName, rpcRcvr)
}
