// Code generated by rpcgen. DO NOT EDIT.

//go:build !tinygo

package appserver

import rpc "github.com/0magnet/gobrpc"

// registerIngressRPC registers *RPCIngressGateway with the reflection-based net/rpc server.
func registerIngressRPC(rpcSrv *rpc.Server, rpcName string, rpcRcvr *RPCIngressGateway) error {
	return rpcSrv.RegisterName(rpcName, rpcRcvr)
}
