// Code generated by rpcgen. DO NOT EDIT.

//go:build tinygo

package appserver

import (
	"encoding/gob"

	rpc "github.com/0magnet/gobrpc"

	"github.com/skycoin/skywire/pkg/app/appnet"
	"github.com/skycoin/skywire/pkg/proxystatus"
	"github.com/skycoin/skywire/pkg/routing"
)

// registerIngressRPC registers each net/rpc method of *RPCIngressGateway as a reflection-free handler.
func registerIngressRPC(rpcSrv *rpc.Server, rpcName string, rpcRcvr *RPCIngressGateway) error {
	rpcSrv.HandleFunc(rpcName+".Accept", func(rpcDec *gob.Decoder) (interface{}, error) {
		rpcArg := new(uint16)
		if err := rpcDec.Decode(rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(AcceptResp)
		return rpcReply, rpcRcvr.Accept(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".AppSettings", func(rpcDec *gob.Decoder) (interface{}, error) {
		rpcArg := new(AppSettingsReq)
		if err := rpcDec.Decode(rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(AppSettingsResp)
		return rpcReply, rpcRcvr.AppSettings(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".CloseConn", func(rpcDec *gob.Decoder) (interface{}, error) {
		rpcArg := new(uint16)
		if err := rpcDec.Decode(rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(struct{})
		return rpcReply, rpcRcvr.CloseConn(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".CloseListener", func(rpcDec *gob.Decoder) (interface{}, error) {
		rpcArg := new(uint16)
		if err := rpcDec.Decode(rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(struct{})
		return rpcReply, rpcRcvr.CloseListener(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".Dial", func(rpcDec *gob.Decoder) (interface{}, error) {
		rpcArg := new(appnet.Addr)
		if err := rpcDec.Decode(rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(DialResp)
		return rpcReply, rpcRcvr.Dial(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".DialWithOptions", func(rpcDec *gob.Decoder) (interface{}, error) {
		rpcArg := new(DialOptionsReq)
		if err := rpcDec.Decode(rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(DialResp)
		return rpcReply, rpcRcvr.DialWithOptions(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".GrowMux", func(rpcDec *gob.Decoder) (interface{}, error) {
		rpcArg := new(GrowMuxReq)
		if err := rpcDec.Decode(rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(int)
		return rpcReply, rpcRcvr.GrowMux(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".Listen", func(rpcDec *gob.Decoder) (interface{}, error) {
		rpcArg := new(appnet.Addr)
		if err := rpcDec.Decode(rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(uint16)
		return rpcReply, rpcRcvr.Listen(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".LocalServices", func(rpcDec *gob.Decoder) (interface{}, error) {
		rpcArg := new(struct{})
		if err := rpcDec.Decode(rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new([]appnet.LocalService)
		return rpcReply, rpcRcvr.LocalServices(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".NoteMuxEvent", func(rpcDec *gob.Decoder) (interface{}, error) {
		rpcArg := new(NoteMuxEventReq)
		if err := rpcDec.Decode(rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(struct{})
		return rpcReply, rpcRcvr.NoteMuxEvent(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".Notify", func(rpcDec *gob.Decoder) (interface{}, error) {
		rpcArg := new(NotifyReq)
		if err := rpcDec.Decode(rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(struct{})
		return rpcReply, rpcRcvr.Notify(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".ProxyStatus", func(rpcDec *gob.Decoder) (interface{}, error) {
		rpcArg := new(struct{})
		if err := rpcDec.Decode(rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(proxystatus.Snapshot)
		return rpcReply, rpcRcvr.ProxyStatus(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".Read", func(rpcDec *gob.Decoder) (interface{}, error) {
		rpcArg := new(ReadReq)
		if err := rpcDec.Decode(rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(ReadResp)
		return rpcReply, rpcRcvr.Read(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".SetAppPort", func(rpcDec *gob.Decoder) (interface{}, error) {
		var rpcArg routing.Port
		if err := rpcDec.Decode(&rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(struct{})
		return rpcReply, rpcRcvr.SetAppPort(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".SetConnectionDuration", func(rpcDec *gob.Decoder) (interface{}, error) {
		var rpcArg int64
		if err := rpcDec.Decode(&rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(struct{})
		return rpcReply, rpcRcvr.SetConnectionDuration(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".SetDeadline", func(rpcDec *gob.Decoder) (interface{}, error) {
		rpcArg := new(DeadlineReq)
		if err := rpcDec.Decode(rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(struct{})
		return rpcReply, rpcRcvr.SetDeadline(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".SetDetailedStatus", func(rpcDec *gob.Decoder) (interface{}, error) {
		rpcArg := new(string)
		if err := rpcDec.Decode(rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(struct{})
		return rpcReply, rpcRcvr.SetDetailedStatus(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".SetError", func(rpcDec *gob.Decoder) (interface{}, error) {
		rpcArg := new(string)
		if err := rpcDec.Decode(rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(struct{})
		return rpcReply, rpcRcvr.SetError(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".SetOTP", func(rpcDec *gob.Decoder) (interface{}, error) {
		rpcArg := new(string)
		if err := rpcDec.Decode(rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(struct{})
		return rpcReply, rpcRcvr.SetOTP(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".SetReadDeadline", func(rpcDec *gob.Decoder) (interface{}, error) {
		rpcArg := new(DeadlineReq)
		if err := rpcDec.Decode(rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(struct{})
		return rpcReply, rpcRcvr.SetReadDeadline(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".SetWriteDeadline", func(rpcDec *gob.Decoder) (interface{}, error) {
		rpcArg := new(DeadlineReq)
		if err := rpcDec.Decode(rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(struct{})
		return rpcReply, rpcRcvr.SetWriteDeadline(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".Write", func(rpcDec *gob.Decoder) (interface{}, error) {
		rpcArg := new(WriteReq)
		if err := rpcDec.Decode(rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(WriteResp)
		return rpcReply, rpcRcvr.Write(rpcArg, rpcReply)
	})
	return nil
}
