package main

import (
	"bytes"
	"strings"
	"testing"
)

func TestMethodRules(t *testing.T) {
	cfg := config{dir: "testdata/sample", specs: []spec{{"S", "registerS"}}, out: "x_tinygo.go", native: "x_native.go"}
	tiny, native, err := generate(cfg)
	if err != nil {
		t.Fatal(err)
	}
	src := string(tiny)
	for _, want := range []string{
		"//go:build tinygo", "// Code generated by rpcgen. DO NOT EDIT.",
		`u "net/url"`, `"time"`,
		`rpcName+".PtrArg"`, "rpcArg := new(time.Duration)", "rpcReply := new(u.URL)",
		`rpcName+".ValArg"`, "var rpcArg []string", "rpcReply := new(map[string]int)",
		`rpcName+".Grouped"`, "rpcArg := new(struct{})",
		"func registerS(rpcSrv *rpc.Server, rpcName string, rpcRcvr *S) error",
	} {
		if !strings.Contains(src, want) {
			t.Errorf("tinygo file lacks %q", want)
		}
	}
	for _, skip := range []string{"unexported", "ThreeArgs", "NonPtrReply", "NoError", "TwoResults", "HiddenArg", "HiddenReply", "Variadic", "NativeOnly"} {
		if strings.Contains(src, `".`+skip+`"`) {
			t.Errorf("tinygo file registers %s, which net/rpc would not", skip)
		}
	}
	if !bytes.Contains(native, []byte("//go:build !tinygo")) || !bytes.Contains(native, []byte("return rpcSrv.RegisterName(rpcName, rpcRcvr)")) {
		t.Errorf("native file:\n%s", native)
	}
}

func TestTargetsMustAgree(t *testing.T) {
	_, _, err := generate(config{dir: "testdata/mismatch", specs: []spec{{"M", "registerM"}}, out: "a.go", native: "b.go"})
	if err == nil || !strings.Contains(err.Error(), "JSOnly only on js/wasm") {
		t.Fatalf("want a target mismatch error, got %v", err)
	}
}

func TestEmbeddedFieldRejected(t *testing.T) {
	_, _, err := generate(config{dir: "testdata/embedded", specs: []spec{{"E", "registerE"}}, out: "a.go", native: "b.go"})
	if err == nil || !strings.Contains(err.Error(), "embeds a field") {
		t.Fatalf("want an embedded field error, got %v", err)
	}
}
