// Command rpcgen writes reflection-free gobrpc handlers for a net/rpc
// receiver, for TinyGo builds where reflect has no Value.Call or Type.Method.
//
// Usage:
//
//	go run ./internal/rpcgen -type T=registerT[,U=registerU] -o x_rpc_tinygo.go -native x_rpc_native.go
//
// It reads the package in -dir (default ".") as the TinyGo build sees it on
// linux/amd64 and on js/wasm, finds every method of *T that net/rpc would
// register, and writes two files. The tinygo file holds
// func registerT(s *rpc.Server, name string, r *T) error, which calls
// s.HandleCall(name+".Method", ...) for each method. The native file holds the
// same function calling s.RegisterName. The argument is decoded on the read
// loop and the method runs in its own goroutine, as with net/rpc.
package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"go/ast"
	"go/build"
	"go/format"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

const (
	gobrpcPath = "github.com/0magnet/gobrpc"
	genHeader  = "// Code generated by rpcgen. DO NOT EDIT.\n\n"
)

// target is one GOOS/GOARCH the tinygo file must be correct for.
type target struct{ goos, goarch string }

var targets = []target{{"linux", "amd64"}, {"js", "wasm"}}

// spec pairs a receiver type with the function name to generate for it.
type spec struct{ typ, fn string }

// config is one rpcgen invocation.
type config struct {
	dir    string
	specs  []spec
	out    string
	native string
}

// method is one net/rpc method of a receiver.
type method struct {
	name     string
	arg      string // arg type with any leading * removed
	argPtr   bool
	reply    string // reply type with the leading * removed
	imports  map[string]string
	position string
}

func (m method) signature() string {
	keys := make([]string, 0, len(m.imports))
	for k := range m.imports {
		keys = append(keys, k+"="+m.imports[k])
	}
	sort.Strings(keys)
	return fmt.Sprintf("(%v %s, *%s) %v", m.argPtr, m.arg, m.reply, keys)
}

func main() {
	cfg, err := parseArgs(os.Args[1:])
	if err != nil {
		fmt.Fprintln(os.Stderr, "rpcgen:", err)
		os.Exit(2)
	}
	tiny, native, err := generate(cfg)
	if err != nil {
		fmt.Fprintln(os.Stderr, "rpcgen:", err)
		os.Exit(1)
	}
	for name, src := range map[string][]byte{cfg.out: tiny, cfg.native: native} {
		if err := os.WriteFile(filepath.Join(cfg.dir, name), src, 0o644); err != nil { //nolint:gosec
			fmt.Fprintln(os.Stderr, "rpcgen:", err)
			os.Exit(1)
		}
	}
}

func parseArgs(args []string) (config, error) {
	var cfg config
	var types string
	fs := flag.NewFlagSet("rpcgen", flag.ContinueOnError)
	fs.StringVar(&cfg.dir, "dir", ".", "package directory")
	fs.StringVar(&types, "type", "", "comma separated Type=funcName pairs")
	fs.StringVar(&cfg.out, "o", "", "output file for the tinygo handlers")
	fs.StringVar(&cfg.native, "native", "", "output file for the native RegisterName helpers")
	if err := fs.Parse(args); err != nil {
		return cfg, err
	}
	if fs.NArg() > 0 {
		return cfg, fmt.Errorf("unexpected arguments %v", fs.Args())
	}
	if cfg.out == "" || cfg.native == "" {
		return cfg, errors.New("-o and -native are required")
	}
	specs, err := parseSpecs(types)
	cfg.specs = specs
	return cfg, err
}

func parseSpecs(s string) ([]spec, error) {
	var specs []spec
	for _, part := range strings.Split(s, ",") {
		typ, fn, ok := strings.Cut(strings.TrimSpace(part), "=")
		if !ok || typ == "" || fn == "" {
			return nil, fmt.Errorf("bad -type entry %q, want Type=funcName", part)
		}
		specs = append(specs, spec{typ, fn})
	}
	return specs, nil
}

// generate returns the tinygo and native file contents for cfg.
func generate(cfg config) (tiny, native []byte, err error) {
	var pkgName string
	perTarget := make([]map[string]map[string]method, len(targets))
	for i, tg := range targets {
		name, methods, err := scan(cfg, tg)
		if err != nil {
			return nil, nil, fmt.Errorf("%s/%s: %w", tg.goos, tg.goarch, err)
		}
		if pkgName != "" && name != pkgName {
			return nil, nil, fmt.Errorf("package name differs between targets: %s and %s", pkgName, name)
		}
		pkgName = name
		perTarget[i] = methods
	}
	for _, sp := range cfg.specs {
		if err := sameMethods(sp.typ, perTarget); err != nil {
			return nil, nil, err
		}
	}
	methods := perTarget[0]

	imports := map[string]string{}
	for _, sp := range cfg.specs {
		for _, m := range methods[sp.typ] {
			for local, p := range m.imports {
				if prev, ok := imports[local]; ok && prev != p {
					return nil, nil, fmt.Errorf("import name %s means both %q and %q", local, prev, p)
				}
				imports[local] = p
			}
		}
	}
	for _, reserved := range []string{"gob", "rpc"} {
		if p, ok := imports[reserved]; ok {
			return nil, nil, fmt.Errorf("argument types use package name %s (%q), which the generated file reserves", reserved, p)
		}
	}

	var b bytes.Buffer
	b.WriteString(genHeader + "//go:build tinygo\n\npackage " + pkgName + "\n\nimport (\n")
	_, mod, err := moduleRoot()
	if err != nil {
		return nil, nil, err
	}
	// Groups are stdlib, third party, then this module, as goimports-reviser orders them.
	groups := [3][]string{{`"encoding/gob"`}, {`rpc "` + gobrpcPath + `"`}, nil}
	for local, p := range imports {
		pkg, err := packageName(p)
		if err != nil {
			return nil, nil, err
		}
		line := strconv.Quote(p)
		if pkg != local {
			line = local + " " + line
		}
		g := 1
		switch {
		case p == mod || strings.HasPrefix(p, mod+"/"):
			g = 2
		case !strings.Contains(strings.Split(p, "/")[0], "."):
			g = 0
		}
		groups[g] = append(groups[g], line)
	}
	for _, g := range groups {
		if len(g) == 0 {
			continue
		}
		sort.Slice(g, func(i, j int) bool { return unaliased(g[i]) < unaliased(g[j]) })
		for _, line := range g {
			b.WriteString("\t" + line + "\n")
		}
		b.WriteString("\n")
	}
	b.WriteString(")\n")

	for _, sp := range cfg.specs {
		names := make([]string, 0, len(methods[sp.typ]))
		for n := range methods[sp.typ] {
			names = append(names, n)
		}
		sort.Strings(names)
		fmt.Fprintf(&b, "\n// %s registers each net/rpc method of *%s as a reflection-free handler.\n", sp.fn, sp.typ)
		fmt.Fprintf(&b, "func %s(rpcSrv *rpc.Server, rpcName string, rpcRcvr *%s) error {\n", sp.fn, sp.typ)
		for _, n := range names {
			m := methods[sp.typ][n]
			fmt.Fprintf(&b, "\trpcSrv.HandleCall(rpcName+%q, func(rpcDec *gob.Decoder) (rpc.CallFunc, error) {\n", "."+m.name)
			if m.argPtr {
				fmt.Fprintf(&b, "\t\trpcArg := new(%s)\n\t\tif err := rpcDec.Decode(rpcArg); err != nil {\n", m.arg)
			} else {
				fmt.Fprintf(&b, "\t\tvar rpcArg %s\n\t\tif err := rpcDec.Decode(&rpcArg); err != nil {\n", m.arg)
			}
			b.WriteString("\t\t\treturn nil, err\n\t\t}\n")
			b.WriteString("\t\treturn func() (any, error) {\n")
			fmt.Fprintf(&b, "\t\t\trpcReply := new(%s)\n", m.reply)
			fmt.Fprintf(&b, "\t\t\treturn rpcReply, rpcRcvr.%s(rpcArg, rpcReply)\n\t\t}, nil\n\t})\n", m.name)
		}
		b.WriteString("\treturn nil\n}\n")
	}
	tiny, err = format.Source(b.Bytes())
	if err != nil {
		return nil, nil, fmt.Errorf("formatting tinygo file: %w\n%s", err, b.Bytes())
	}

	b.Reset()
	b.WriteString(genHeader + "//go:build !tinygo\n\npackage " + pkgName + "\n\nimport rpc \"" + gobrpcPath + "\"\n")
	for _, sp := range cfg.specs {
		fmt.Fprintf(&b, "\n// %s registers *%s with the reflection-based net/rpc server.\n", sp.fn, sp.typ)
		fmt.Fprintf(&b, "func %s(rpcSrv *rpc.Server, rpcName string, rpcRcvr *%s) error {\n\treturn rpcSrv.RegisterName(rpcName, rpcRcvr)\n}\n", sp.fn, sp.typ)
	}
	native, err = format.Source(b.Bytes())
	if err != nil {
		return nil, nil, fmt.Errorf("formatting native file: %w", err)
	}
	return tiny, native, nil
}

func sameMethods(typ string, perTarget []map[string]map[string]method) error {
	base := perTarget[0][typ]
	for i := 1; i < len(perTarget); i++ {
		other := perTarget[i][typ]
		var diffs []string
		for n, m := range base {
			o, ok := other[n]
			switch {
			case !ok:
				diffs = append(diffs, fmt.Sprintf("%s only on %s/%s (%s)", n, targets[0].goos, targets[0].goarch, m.position))
			case o.signature() != m.signature():
				diffs = append(diffs, fmt.Sprintf("%s differs: %s vs %s", n, m.signature(), o.signature()))
			}
		}
		for n, o := range other {
			if _, ok := base[n]; !ok {
				diffs = append(diffs, fmt.Sprintf("%s only on %s/%s (%s)", n, targets[i].goos, targets[i].goarch, o.position))
			}
		}
		if len(diffs) > 0 {
			sort.Strings(diffs)
			return fmt.Errorf("methods of *%s differ between targets:\n\t%s", typ, strings.Join(diffs, "\n\t"))
		}
	}
	return nil
}

// scan parses the files the tinygo build selects for tg and returns the
// package name and the net/rpc methods of each requested type.
func scan(cfg config, tg target) (string, map[string]map[string]method, error) {
	ctx := build.Default
	ctx.GOOS, ctx.GOARCH = tg.goos, tg.goarch
	ctx.BuildTags = []string{"tinygo"}
	ctx.CgoEnabled = false

	entries, err := os.ReadDir(cfg.dir)
	if err != nil {
		return "", nil, err
	}
	want := map[string]bool{}
	for _, sp := range cfg.specs {
		want[sp.typ] = true
	}
	fset := token.NewFileSet()
	methods := map[string]map[string]method{}
	found := map[string]bool{}
	pkgName := ""
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") || name == cfg.out || name == cfg.native {
			continue
		}
		ok, err := ctx.MatchFile(cfg.dir, name)
		if err != nil {
			return "", nil, err
		}
		if !ok {
			continue
		}
		f, err := parser.ParseFile(fset, filepath.Join(cfg.dir, name), nil, parser.SkipObjectResolution)
		if err != nil {
			return "", nil, err
		}
		if pkgName == "" {
			pkgName = f.Name.Name
		}
		for _, decl := range f.Decls {
			switch d := decl.(type) {
			case *ast.GenDecl:
				for _, s := range d.Specs {
					ts, ok := s.(*ast.TypeSpec)
					if !ok || !want[ts.Name.Name] {
						continue
					}
					found[ts.Name.Name] = true
					if st, ok := ts.Type.(*ast.StructType); ok {
						for _, fld := range st.Fields.List {
							if len(fld.Names) == 0 {
								return "", nil, fmt.Errorf("%s: %s embeds a field, and promoted methods are not supported", fset.Position(fld.Pos()), ts.Name.Name)
							}
						}
					}
				}
			case *ast.FuncDecl:
				typ := recvType(d)
				if typ == "" || !want[typ] {
					continue
				}
				m, ok, err := rpcMethod(fset, f, d)
				if err != nil {
					return "", nil, err
				}
				if !ok {
					continue
				}
				if methods[typ] == nil {
					methods[typ] = map[string]method{}
				}
				methods[typ][m.name] = m
			}
		}
	}
	for t := range want {
		if !found[t] {
			return "", nil, fmt.Errorf("type %s not found in %s", t, cfg.dir)
		}
		if len(methods[t]) == 0 {
			return "", nil, fmt.Errorf("type %s has no net/rpc methods", t)
		}
	}
	return pkgName, methods, nil
}

// recvType returns the base type name of a method receiver, or "" for a
// function or a generic receiver.
func recvType(d *ast.FuncDecl) string {
	if d.Recv == nil || len(d.Recv.List) != 1 {
		return ""
	}
	t := d.Recv.List[0].Type
	if s, ok := t.(*ast.StarExpr); ok {
		t = s.X
	}
	if id, ok := t.(*ast.Ident); ok {
		return id.Name
	}
	return ""
}

// rpcMethod applies net/rpc's suitableMethods rules to d.
func rpcMethod(fset *token.FileSet, f *ast.File, d *ast.FuncDecl) (method, bool, error) {
	if !d.Name.IsExported() {
		return method{}, false, nil
	}
	var params []ast.Expr
	for _, p := range d.Type.Params.List {
		n := len(p.Names)
		if n == 0 {
			n = 1
		}
		for i := 0; i < n; i++ {
			params = append(params, p.Type)
		}
	}
	if len(params) != 2 {
		return method{}, false, nil
	}
	res := d.Type.Results
	if res == nil || len(res.List) != 1 || len(res.List[0].Names) > 1 {
		return method{}, false, nil
	}
	if id, ok := res.List[0].Type.(*ast.Ident); !ok || id.Name != "error" {
		return method{}, false, nil
	}
	if _, ok := params[0].(*ast.Ellipsis); ok {
		return method{}, false, nil
	}
	replyStar, ok := params[1].(*ast.StarExpr)
	if !ok {
		return method{}, false, nil
	}
	if !exportedOrBuiltin(params[0]) || !exportedOrBuiltin(params[1]) {
		return method{}, false, nil
	}

	m := method{
		name:     d.Name.Name,
		reply:    exprString(fset, replyStar.X),
		imports:  map[string]string{},
		position: fset.Position(d.Pos()).String(),
	}
	arg := params[0]
	if s, ok := arg.(*ast.StarExpr); ok {
		m.argPtr = true
		arg = s.X
	}
	m.arg = exprString(fset, arg)

	for _, e := range []ast.Expr{arg, replyStar.X} {
		var err error
		ast.Inspect(e, func(n ast.Node) bool {
			sel, ok := n.(*ast.SelectorExpr)
			if !ok || err != nil {
				return err == nil
			}
			id, ok := sel.X.(*ast.Ident)
			if !ok {
				return true
			}
			p, ok := importPath(f, id.Name)
			if !ok {
				err = fmt.Errorf("%s: no import named %s for %s", m.position, id.Name, d.Name.Name)
				return false
			}
			m.imports[id.Name] = p
			return false
		})
		if err != nil {
			return method{}, false, err
		}
	}
	return m, true, nil
}

var builtinTypes = map[string]bool{
	"any": true, "bool": true, "byte": true, "complex64": true, "complex128": true,
	"error": true, "float32": true, "float64": true, "int": true, "int8": true,
	"int16": true, "int32": true, "int64": true, "rune": true, "string": true,
	"uint": true, "uint8": true, "uint16": true, "uint32": true, "uint64": true,
	"uintptr": true,
}

// exportedOrBuiltin mirrors net/rpc's isExportedOrBuiltinType on source.
// Unnamed composite types have no package path, so they count as builtin.
func exportedOrBuiltin(e ast.Expr) bool {
	for {
		s, ok := e.(*ast.StarExpr)
		if !ok {
			break
		}
		e = s.X
	}
	switch t := e.(type) {
	case *ast.Ident:
		return builtinTypes[t.Name] || t.IsExported()
	case *ast.SelectorExpr:
		return t.Sel.IsExported()
	case *ast.ParenExpr:
		return exportedOrBuiltin(t.X)
	case *ast.IndexExpr, *ast.IndexListExpr:
		return false
	default:
		return true
	}
}

func exprString(fset *token.FileSet, e ast.Expr) string {
	var b bytes.Buffer
	if err := printer.Fprint(&b, fset, e); err != nil {
		panic(err)
	}
	return b.String()
}

// importPath finds the import of f that the identifier local refers to.
func importPath(f *ast.File, local string) (string, bool) {
	for _, imp := range f.Imports {
		p, err := strconv.Unquote(imp.Path.Value)
		if err != nil {
			continue
		}
		if imp.Name != nil {
			if imp.Name.Name == local {
				return p, true
			}
			continue
		}
		if name, err := packageName(p); err == nil && name == local {
			return p, true
		}
	}
	return "", false
}

var pkgNameCache = map[string]string{}

// packageName reads the package clause of import path p from the module,
// its vendor directory or GOROOT.
func packageName(p string) (string, error) {
	if n, ok := pkgNameCache[p]; ok {
		return n, nil
	}
	root, mod, err := moduleRoot()
	if err != nil {
		return "", err
	}
	var dirs []string
	if p == mod || strings.HasPrefix(p, mod+"/") {
		dirs = append(dirs, filepath.Join(root, strings.TrimPrefix(p, mod)))
	}
	dirs = append(dirs, filepath.Join(root, "vendor", p), filepath.Join(build.Default.GOROOT, "src", p))
	for _, dir := range dirs {
		entries, err := os.ReadDir(dir)
		if err != nil {
			continue
		}
		for _, e := range entries {
			n := e.Name()
			if e.IsDir() || !strings.HasSuffix(n, ".go") || strings.HasSuffix(n, "_test.go") {
				continue
			}
			f, err := parser.ParseFile(token.NewFileSet(), filepath.Join(dir, n), nil, parser.PackageClauseOnly)
			if err != nil || f.Name.Name == "main" || f.Name.Name == "documentation" {
				continue
			}
			pkgNameCache[p] = f.Name.Name
			return f.Name.Name, nil
		}
	}
	return "", fmt.Errorf("cannot find package %s (last element %s)", p, path.Base(p))
}

var modRoot, modPath string

// moduleRoot finds the enclosing go.mod from the working directory.
func moduleRoot() (string, string, error) {
	if modRoot != "" {
		return modRoot, modPath, nil
	}
	dir, err := os.Getwd()
	if err != nil {
		return "", "", err
	}
	for {
		data, err := os.ReadFile(filepath.Join(dir, "go.mod")) //nolint:gosec
		if err == nil {
			for _, line := range strings.Split(string(data), "\n") {
				if rest, ok := strings.CutPrefix(strings.TrimSpace(line), "module "); ok {
					modRoot, modPath = dir, strings.Trim(strings.TrimSpace(rest), `"`)
					return modRoot, modPath, nil
				}
			}
			return "", "", errors.New("go.mod has no module line")
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", "", errors.New("no go.mod found")
		}
		dir = parent
	}
}

// unaliased returns the quoted path of an import line for sorting.
func unaliased(line string) string {
	if i := strings.IndexByte(line, '"'); i >= 0 {
		return line[i:]
	}
	return line
}
