// Code generated by rpcgen. DO NOT EDIT.

//go:build !tinygo

package router

import rpc "github.com/0magnet/gobrpc"

// registerRPCGateway registers *RPCGateway with the reflection-based net/rpc server.
func registerRPCGateway(rpcSrv *rpc.Server, rpcName string, rpcRcvr *RPCGateway) error {
	return rpcSrv.RegisterName(rpcName, rpcRcvr)
}

// RegisterSetupRPCGateway registers *SetupRPCGateway with the reflection-based net/rpc server.
func RegisterSetupRPCGateway(rpcSrv *rpc.Server, rpcName string, rpcRcvr *SetupRPCGateway) error {
	return rpcSrv.RegisterName(rpcName, rpcRcvr)
}

// registerTransportQueryRPCGateway registers *TransportQueryRPCGateway with the reflection-based net/rpc server.
func registerTransportQueryRPCGateway(rpcSrv *rpc.Server, rpcName string, rpcRcvr *TransportQueryRPCGateway) error {
	return rpcSrv.RegisterName(rpcName, rpcRcvr)
}
