// Code generated by rpcgen. DO NOT EDIT.

//go:build tinygo

package router

import (
	"encoding/gob"

	rpc "github.com/0magnet/gobrpc"

	"github.com/skycoin/skywire/pkg/routing"
)

// registerRPCGateway registers each net/rpc method of *RPCGateway as a reflection-free handler.
func registerRPCGateway(rpcSrv *rpc.Server, rpcName string, rpcRcvr *RPCGateway) error {
	rpcSrv.HandleFunc(rpcName+".AddEdgeRules", func(rpcDec *gob.Decoder) (interface{}, error) {
		var rpcArg routing.EdgeRules
		if err := rpcDec.Decode(&rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(bool)
		return rpcReply, rpcRcvr.AddEdgeRules(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".AddIntermediaryRules", func(rpcDec *gob.Decoder) (interface{}, error) {
		var rpcArg []routing.Rule
		if err := rpcDec.Decode(&rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(bool)
		return rpcReply, rpcRcvr.AddIntermediaryRules(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".DelRules", func(rpcDec *gob.Decoder) (interface{}, error) {
		var rpcArg []routing.RouteID
		if err := rpcDec.Decode(&rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(bool)
		return rpcReply, rpcRcvr.DelRules(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".ReserveIDs", func(rpcDec *gob.Decoder) (interface{}, error) {
		var rpcArg uint8
		if err := rpcDec.Decode(&rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new([]routing.RouteID)
		return rpcReply, rpcRcvr.ReserveIDs(rpcArg, rpcReply)
	})
	return nil
}

// RegisterSetupRPCGateway registers each net/rpc method of *SetupRPCGateway as a reflection-free handler.
func RegisterSetupRPCGateway(rpcSrv *rpc.Server, rpcName string, rpcRcvr *SetupRPCGateway) error {
	rpcSrv.HandleFunc(rpcName+".Capabilities", func(rpcDec *gob.Decoder) (interface{}, error) {
		rpcArg := new(CapabilitiesArgs)
		if err := rpcDec.Decode(rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(CapabilitiesReply)
		return rpcReply, rpcRcvr.Capabilities(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".CascadeSignInstall", func(rpcDec *gob.Decoder) (interface{}, error) {
		rpcArg := new(CascadeSignInstallArgs)
		if err := rpcDec.Decode(rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(CascadeSignInstallReply)
		return rpcReply, rpcRcvr.CascadeSignInstall(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".CascadeSignReserve", func(rpcDec *gob.Decoder) (interface{}, error) {
		rpcArg := new(CascadeSignReserveArgs)
		if err := rpcDec.Decode(rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(CascadeSignReserveReply)
		return rpcReply, rpcRcvr.CascadeSignReserve(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".DialRouteGroup", func(rpcDec *gob.Decoder) (interface{}, error) {
		var rpcArg routing.BidirectionalRoute
		if err := rpcDec.Decode(&rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(routing.EdgeRules)
		return rpcReply, rpcRcvr.DialRouteGroup(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".DialRouteGroupBatch", func(rpcDec *gob.Decoder) (interface{}, error) {
		rpcArg := new(routing.BidirectionalRouteBatch)
		if err := rpcDec.Decode(rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(routing.BidirectionalRouteBatchReply)
		return rpcReply, rpcRcvr.DialRouteGroupBatch(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".HealthCheck", func(rpcDec *gob.Decoder) (interface{}, error) {
		rpcArg := new(HealthCheckArgs)
		if err := rpcDec.Decode(rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(HealthCheckReply)
		return rpcReply, rpcRcvr.HealthCheck(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".RelayPeers", func(rpcDec *gob.Decoder) (interface{}, error) {
		rpcArg := new(RelayPeersArgs)
		if err := rpcDec.Decode(rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(RelayPeersReply)
		return rpcReply, rpcRcvr.RelayPeers(rpcArg, rpcReply)
	})
	rpcSrv.HandleFunc(rpcName+".SignTransportQuery", func(rpcDec *gob.Decoder) (interface{}, error) {
		rpcArg := new(SignTransportQueryArgs)
		if err := rpcDec.Decode(rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(SignTransportQueryReply)
		return rpcReply, rpcRcvr.SignTransportQuery(rpcArg, rpcReply)
	})
	return nil
}

// registerTransportQueryRPCGateway registers each net/rpc method of *TransportQueryRPCGateway as a reflection-free handler.
func registerTransportQueryRPCGateway(rpcSrv *rpc.Server, rpcName string, rpcRcvr *TransportQueryRPCGateway) error {
	rpcSrv.HandleFunc(rpcName+".Query", func(rpcDec *gob.Decoder) (interface{}, error) {
		rpcArg := new(TransportQuery)
		if err := rpcDec.Decode(rpcArg); err != nil {
			return nil, err
		}
		rpcReply := new(TransportQueryResponse)
		return rpcReply, rpcRcvr.Query(rpcArg, rpcReply)
	})
	return nil
}
