// Code generated by rpcgen. DO NOT EDIT.

//go:build !tinygo

package pty

import rpc "github.com/0magnet/gobrpc"

// registerWhitelistGateway registers *WhitelistGateway with the reflection-based net/rpc server.
func registerWhitelistGateway(rpcSrv *rpc.Server, rpcName string, rpcRcvr *WhitelistGateway) error {
	return rpcSrv.RegisterName(rpcName, rpcRcvr)
}

// registerLocalPtyGateway registers *LocalPtyGateway with the reflection-based net/rpc server.
func registerLocalPtyGateway(rpcSrv *rpc.Server, rpcName string, rpcRcvr *LocalPtyGateway) error {
	return rpcSrv.RegisterName(rpcName, rpcRcvr)
}

// registerProxiedPtyGateway registers *ProxiedPtyGateway with the reflection-based net/rpc server.
func registerProxiedPtyGateway(rpcSrv *rpc.Server, rpcName string, rpcRcvr *ProxiedPtyGateway) error {
	return rpcSrv.RegisterName(rpcName, rpcRcvr)
}

// registerSessionPtyGateway registers *sessionPtyGateway with the reflection-based net/rpc server.
func registerSessionPtyGateway(rpcSrv *rpc.Server, rpcName string, rpcRcvr *sessionPtyGateway) error {
	return rpcSrv.RegisterName(rpcName, rpcRcvr)
}
