// Code generated by rpcgen. DO NOT EDIT.

//go:build tinygo

package appevent

import (
	"encoding/gob"

	rpc "github.com/0magnet/gobrpc"
)

// registerRPCGateway registers each net/rpc method of *RPCGateway as a reflection-free handler.
func registerRPCGateway(rpcSrv *rpc.Server, rpcName string, rpcRcvr *RPCGateway) error {
	rpcSrv.HandleCall(rpcName+".Notify", func(rpcDec *gob.Decoder) (rpc.CallFunc, error) {
		rpcArg := new(Event)
		if err := rpcDec.Decode(rpcArg); err != nil {
			return nil, err
		}
		return func() (any, error) {
			rpcReply := new(struct{})
			return rpcReply, rpcRcvr.Notify(rpcArg, rpcReply)
		}, nil
	})
	return nil
}
