// Code generated by rpcgen. DO NOT EDIT.

//go:build !tinygo

package appevent

import rpc "github.com/0magnet/gobrpc"

// registerRPCGateway registers *RPCGateway with the reflection-based net/rpc server.
func registerRPCGateway(rpcSrv *rpc.Server, rpcName string, rpcRcvr *RPCGateway) error {
	return rpcSrv.RegisterName(rpcName, rpcRcvr)
}
